### ISSUE TITLE
Write files in compressed format.

### ISSUE THREAD

**Issue by tokusyu** [blockchain-etl/ethereum-etl#103]
It is very useful if this etl tool could  output csv files in compressed format.
Because the size of output files are huge and analyzing tool like pandas can read gzip file directly.

**Comment by tokusyu** [comment]
Thanks, but where is your code? :)

**Comment by elim0322** [comment]
I wrote it for work so I have to check with my colleague first on Monday :) I’ll let you know

**Comment by tokusyu** [comment]
Excellent!

**Comment by elim0322** [comment]
Reminding myself to do this

**Comment by tokusyu** [comment]
I solved this problem using Apache Spark with additional tasks.
I changed my mind that this issue should be solved outside this software.
Thanks.
