### ISSUE TITLE
recover excutional bit on shell files

### ISSUE THREAD

**Issue by tokusyu** [blockchain-etl/ethereum-etl#107]
I found that on the latest master branch there are no excute bit on shell scripts.
Ex: git ls-files -s export_all.sh
-> 100644

So this script isn’t executable.
Could someone kindly recover execute bits?

Or completely move to python verdion of export_all (I love it) and then remove shell version from master ; )

**Comment by medvedev1088** [comment]
Thanks for spotting this! I just pushed a commit to recover it:

```
git ls-files -s export_all.sh
100755 87e65537f57c776f9e41c4a04d4910ff248de457 0       export_all.sh
```

I'm going to remove the shell version once the Dockerfile supports IPC.
