### ISSUE TITLE
Missing contracts created in internal transactions

### ISSUE THREAD

**Issue by pieterhartel** [blockchain-etl/ethereum-etl#134]
I have tried to find the address of all verified smart contracts from etherscan.io on google big query ( table bigquery-public-data.ethereum_blockchain.contracts ) and it seems that all contracts that have been created by an internal transaction are missing from the google big query data base. Is that indeed the case? 

Here is my query:

```
#standardSQL
SELECT
  COUNT(verifieds.address)
FROM
  `bocktest-224205.etherscan.contractsVerified` AS verifieds
WHERE
  LOWER(verifieds.address) NOT IN (
  SELECT
    LOWER(contracts.address)
  FROM
    `bigquery-public-data.ethereum_blockchain.contracts` AS contracts)
LIMIT
  10
```
1406 contracts out of a total of 48839 verified smart contracts are missing...

Here are three examples :

[https://etherscan.io/address/0x381c23667cdb85514b8bc8ebe7406fec9d0c8f3c]
[https://etherscan.io/address/0xada83270510b6284e27c757096d660f0fcf6a90b]
[https://etherscan.io/address/0xa27d94001a2a58395b1bb34ea2f842912a906163]

Try this to see that these internal contracts are indeed missing:

```
#standardSQL
SELECT
  *
FROM
  `bigquery-public-data.ethereum_blockchain.contracts`
WHERE
  LOWER(address) = '0x381c23667cdb85514b8bc8ebe7406fec9d0c8f3c'
LIMIT
  10
```
--pieter

**Comment by medvedev1088** [comment]
Thanks for reporting this. You are correct - the contracts created in internal transactions are missing. This is one of the limitations https://github.com/blockchain-etl/ethereum-etl#limitations. We are working on adding those to the dataset https://github.com/blockchain-etl/ethereum-etl-airflow/issues/8.

Meanwhile you can query all contract addresses and bytecode from the traces table:

```
#standardSQL
select to_address
from `bigquery-public-data.ethereum_blockchain.traces`
where trace_type = 'create'
and to_address is not null
```

The bytecode is in the `output` column.

**Comment by pieterhartel** [comment]
Thank you for your swift feedback and the suggestion to use the traces table. I had indeed overlooked the limitations section on GitHub. I have also tried out my query with the traces table instead of the contracts table like so:

```
#standardSQL
SELECT verifieds.address
FROM `blocktest-224213.etherscan.contractsVerified` AS verifieds
WHERE LOWER(verifieds.address) NOT IN (
  SELECT LOWER(traces.to_address)
  FROM `bigquery-public-data.ethereum_blockchain.traces` AS traces
  WHERE trace_type = 'create' AND to_address IS NOT NULL)
LIMIT 10
```

Now there are only 14 verified contracts unaccounted for. I looked a few up on etherscan and it seems that this has something to do with the error status of the contract. Take this one below as an example, which has run out of gas during the create transaction:

[https://etherscan.io/address/0x62bc2aec45b6ab216c198c105c78093284b2327e]

--pieter

**Comment by medvedev1088** [comment]
Yes that's an interesting case. Somehow Parity doesn't return the contract address when a transaction (or  a message call) failed https://etherscan.io/vmtrace?txhash=0x1fb7448b3a4d9096385576edc7712fa202cff341b25b335281aee73faefe8a1a&type=parity#raw. For successful contract creations the contract address is in `result.address` field, which we put into `to_address` in the BigQuery traces table. 

This behaviour in Parity is inconsistent with transaction receipts. For example, the receipt for that transaction `0x1fb7448b3a4d9096385576edc7712fa202cff341b25b335281aee73faefe8a1a` contains contract_address in it. If you are up for it you can submit an issue to Parity asking what's the rationale for not including contract address in failed traces, and if there is no rationale, submit a bug.

**Comment by Guangye-C** [comment]
It seems even when a contract was successfully created it, it may still not be in `bigquery-public-data.crypto_ethereum.traces`

For example, I cannot find the Compound Wrapped BTC:  https://etherscan.io/txs?a=0xc11b1268c1a384e55c48c2391d8d480264a3a7f4&p=296

Is it that as long as there was one failed transaction involving this contract, the contract will not appear in bigquery at all even if it was created successfully?

**Comment by medvedev1088** [comment]
@Guangye-C I can find it in the traces table:
```
SELECT count(1)
FROM `bigquery-public-data.crypto_ethereum.traces`
where to_address = '0xc11b1268c1a384e55c48c2391d8d480264a3a7f4'
and trace_type = 'create'
```

It's also in the contracts table.

**Comment by Guangye-C** [comment]
@medvedev1088 Thank you! I see where I went wrong.

**Comment by Guangye-C** [comment]
@medvedev1088 A follow-up question. If I'm looking for all transactions involving a specific token, is there a place to find it other than the token_transfer dataset on bigquery? Does the ethereum token_transfer dataset include internal transfers, or only those made by externally owned account? Sorry if the answer is obvious, I'm new to Ethereum data. 

Thank you for your help!
