### ISSUE TITLE
traceAddress field on Internal Transactions

### ISSUE THREAD

**Issue by tokusyu** [blockchain-etl/ethereum-etl#135]
I want to tell root trace from each transactions using traceAddress field, to make status field before byzantium HF.
The latest version of this ETL tool returns null on traceAddress field for both root trace and end traces.

https://github.com/paritytech/wiki/blob/master/JSONRPC-trace-module.md#traceaddress-field

It would be nice if the tool returns the information to tell root trace from other traces.

**Comment by medvedev1088** [comment]
Right now trace_address is null in for which Parity returned `[]`, i.e. all root traces. Could you clarify what you meant by "both root trace and end traces"?

**Comment by tokusyu** [comment]
OK.
For example. transition hash: 0xcd00c809d674717642222309c5cb5d40083b010a1a2f112b9849f6874186e5e1
has 3 rows on trace table.

1. call_type: call, gas: 2081185, gas_used: 48322, subtraces:1, trace_address: null
2. call_type: callcode , gas: 2072091, gas_used: 48229, subtraces:1, trace_address:1
3. call_type: call, gas: 2017169, gas_used:0, subtraces:0, trace_address:null

I think 1st row is the root of traces but 3rd row (maybe end of trace) also returns null on trace_address field.

And old version of this etl tool returned same transaction like below.
1. ..., trace_address: []
2. ..., trace_address:[null]
3. ..., trace_address:[null]

So I could easily tell what was the root trace!

**Comment by medvedev1088** [comment]
Hmm, that's interesting. What branch are you using? I just tried on develop branch and I get 3 traces with correct addresses:

> python ethereumetl export_traces -s 116593 -e 116593  -o traces.csv

```
call_type | reward_type | gas | gas_used | subtraces | trace_address
-- | -- | -- | -- | -- | --
call |   | 2081185 | 48322 | 1 |  null
callcode |   | 2072091 | 48229 | 1 | 0
call |   | 2017169 | 0 | 0 | 0,0
```

I also checked in the BigQuery dataset, and get the same result:

```#standardSQL
select * 
from `bigquery-public-data.ethereum_blockchain.traces`
where transaction_hash = '0xcd00c809d674717642222309c5cb5d40083b010a1a2f112b9849f6874186e5e1'
```

**Comment by tokusyu** [comment]
Thanks.
I found the cause is my broken schema.
The result you showed me is what I wanted!
I'm using pip version and I'm glad I don't need to re-run to extract traces from genesis block!
