### ISSUE TITLE
Exporting traces timeouts

### ISSUE THREAD

**Issue by lukaskai** [blockchain-etl/ethereum-etl#137]
Hello, I have an issue with exporting the traces from Parity. Setting batches even to 1 block per file, and timeout to 600 seconds, the export of certain block traces timeouts. 

A very good example block: 3805005. It always timeouts and interestingly there are over 100 failed internal txs (https://etherscan.io/txsInternal?block=3805005). Therefore, it always timeouts wihle running the export script. Or same with block: 3805016.

Other example block batch also timeouts: 2370400- 2370500. There are more as well.

Anyone having simillar issues or ideas how to fix?

**Comment by medvedev1088** [comment]
Thanks for reporting this issue! 

What instance type are you using for the Parity node? I've been using `n1-highmem-2 (2 vCPUs, 13 GB memory)` in GCP and all the blocks are exported within the default timeout. I suspect the bottleneck may be memory in your case?

**Comment by lukaskai** [comment]
Thanks, it worked. It seems that I had too low IPC_Timeout set up, as well as instance setup was not right. With m5 large it seems to be working like charm. Thanks guys, appreciate you help.

**Comment by cxd1995** [comment]
@tokusyu @lukaskai 
I had same problem. Could you teach me how to change default _ipc_timeout?

**Comment by logiclord** [comment]
`export DEFAULT_TIMEOUT=6000` or `--timeout 6000` flag should work
