### ISSUE TITLE
web3.exceptions.InvalidAddress

### ISSUE THREAD

**Issue by disadone** [blockchain-etl/ethereum-etl#138]
When I executed 

>proxychains4 ethereumetl export_token_transfers --start-block 6463105 --end-block 6990999 --provider-uri file://root/.ethereum/geth.ipc --output token_transfers.csv --tokens 0x81e74a3ea4bab2277aa3b941e9d9f37b08ac5374 

I got

> web3.exceptions.InvalidAddress:`('Web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).', '0x81e74a3ea4bab2277aa3b941e9d9f37b08ac5374')

It says that I should file it as a bug.... So I am here.

I was running ethereum-go using docker. ethereum-etl was not in docker environment.

**Comment by tokusyu** [comment]
Convert your token address 0x81... using below service.
https://piyolab.github.io/sushiether/RunScrapboxCode/?web3=1.0.0-beta.33&code=https://scrapbox.io/api/code/sushiether/web3.js_-_Ethereum_のアドレスをチェックサム付きアドレスに変換する/demo.js

**Comment by disadone** [comment]
Oh, em.. It seems a easy problem. Thank you!
