### ISSUE TITLE
Missing Status Column exporting receipts

### ISSUE THREAD

**Issue by cxd1995** [blockchain-etl/ethereum-etl#142]
@medvedev1088 
We found that sometimes status column are missing in the receipt table using geth.
Transactions in the first four million blocks do not have the status column.
![image](https://user-images.githubusercontent.com/45622921/51103001-24610600-181c-11e9-83a9-1c79b12eb1f2.png)

After Block 4,300,000, the receipt table has status column and is filled with zero or one.
![image](https://user-images.githubusercontent.com/45622921/51103021-32168b80-181c-11e9-86a9-cdec6e086e09.png)

So how could we figure out failed transaction in the first four million blocks

**Comment by medvedev1088** [comment]
Yeah I found this also when I plotted successful vs failed transactions here https://medium.com/@medvedev1088/more-blockchain-analysis-on-bigquery-92a863137f01. `receipt_status` column was added to Ethereum protocol in Bysantium release that’s why the data is missing before October 14, 2017. 

As a workaround `status` field in traces can be used.

**Comment by cxd1995** [comment]
Thanks! 
BUT how could we figure out failed transactions in trace table?Error column might be not enough. Sometimes error happend in part of the transaction in the trace table. BUT it still succeed finially. 
![image](https://user-images.githubusercontent.com/45622921/51104045-e960d180-181f-11e9-88f3-589c881a0378.png)
![image](https://user-images.githubusercontent.com/45622921/51104073-03021900-1820-11e9-9c38-b64f9eed3b71.png)

**Comment by medvedev1088** [comment]
You are right it may be tricky. I believe if you filter only top level traces and look at the ones that have error null, those are succeeded transactions, all others are failed.
