### ISSUE TITLE
Auto sync DB from ethereum node.

### ISSUE THREAD

**Issue by Aminadav** [blockchain-etl/ethereum-etl#145]
Do you have an idea how to implement an ongoing process that checks each block (after X confirmations), and outputs the data to console or append it to CSV?

This way it will be easy to create software that monitors the mainnet.

Is it currently supported?
Is it going to be supported?

**Comment by medvedev1088** [comment]
feature/streaming branch in this repository contains stream.py file with PubSubExporter. Also there are instructions here for deploying to GCP https://github.com/blockchain-etl/ethereum-etl-streaming

**Comment by Aminadav** [comment]
Great. Exactly what I needed. Thanks.
