### ISSUE TITLE
no module name ethereumetl.cli, 'ethereumetl' is not a package

### ISSUE THREAD

**Issue by ghost** [blockchain-etl/ethereum-etl#146]
![error1](https://user-images.githubusercontent.com/26707639/52394141-43ce1480-2ae4-11e9-8937-bce8e9aad70a.png)

**Comment by leexitong** [comment]
windows 10, python 3.7

**Comment by t2y** [comment]
I think this issue is about installing python pacakge, not ethereum-etl itself.

You should use pip command to install python package. Or, Anaconda and conda command might be help for you if you don't have the knowledge to setup the build environment on Windows machine.
