### ISSUE TITLE
How Could I distinguish ERC20/721 ?

### ISSUE THREAD

**Issue by ellen4** [blockchain-etl/ethereum-etl#148]
Hello, I collected **token transfer** information via ethereum-etl.

```bash
ethereumetl export_token_transfers --start-block 0 --end-block 500000 \
--provider-uri file://$HOME/Library/Ethereum/geth.ipc --output token_transfers.csv
```

Now I get **token_transfers.csv** file. 

How can I distinguish ERC20/721 ?

Thanks.

**Comment by medvedev1088** [comment]
One way is to use export_contracts command, the output of which has is_erc20 and is_erc721 fields https://github.com/blockchain-etl/ethereum-etl#export_contracts

**Comment by ellen4** [comment]
Thank you. It helped a lot.
