### ISSUE TITLE
Address is not exist (info, transfer)

### ISSUE THREAD

**Issue by ellen4** [blockchain-etl/ethereum-etl#150]
Hello, I made up two tables.

First one is **token transfer** data and the other one is **token info** data

I discovered two tables, And I found something weird.

token **CPT (contents protocol) (=Address '0x9b62513c8a27290cf6a7a9e29386e600245ea819'**) exists in token transfer table.

But not in token info table.

How could it happen? is it wrong situation or it could be ?

Both of the tables are made with data through whole block data.

**Comment by medvedev1088** [comment]
Hi, that's a known limitation https://github.com/blockchain-etl/ethereum-etl/issues/134. The contracts created in internal transactions are missing in the contracts table. In order to access them you'd need to export traces.
