### ISSUE TITLE
Error in exporting traces using Parity

### ISSUE THREAD

**Issue by cxd1995** [blockchain-etl/ethereum-etl#151]
@medvedev1088 
We used Parity to export traces. It works perfectly for almost every block.
BUT error happens in some block ranges, such as 2,280,000~2,400,000 and 3800000~4,000,000.
 **Error:web3.utils.threads.Timeout: 60 seconds**
![image](https://user-images.githubusercontent.com/45622921/53099550-01cfb480-3561-11e9-8336-71ba4805299f.png)

Our server has far more than 8 GB memory. Maybe we could change default time. But we could not figure out  the correct command

**Comment by medvedev1088** [comment]
Hi, thanks for reporting this. Try with this PR https://github.com/blockchain-etl/ethereum-etl/pull/152. It adds -t option for timeout.

**Comment by cxd1995** [comment]
Thanks. 
We have updated files including export_traces.py and auto.py in our server.
And the default time are set at 3000, which is long enough. 
BUT same error still happens.

**Comment by medvedev1088** [comment]
Does it timeout after 60 seconds or 50 minutes?

**Comment by cxd1995** [comment]
It still timeouts after 50 minutes

**Comment by tokusyu** [comment]
Hi, My setting is 
 DEFAULT_IPC_TIMEOUT = 6000 

And I'm using AWS EC2 m5.large.

**Comment by medvedev1088** [comment]
Also check your EBS volume is performant enough - EBS(type: gp2, IOPS:7500)

**Comment by cxd1995** [comment]
Thanks!
We have deleted large files to ensure enough volume(more than 100G) in our server.
And We will try to set default_IPC_timeout=6000.

**Comment by cxd1995** [comment]
We found that some single blocks are extremely large and the program get error in these blocks.
We finally have extracted traces of these blocks successfully, one at a time.

**Comment by medvedev1088** [comment]
Could you also specify you Parity version? It's possible there were changes that made the API slower.

**Comment by cxd1995** [comment]
The Parity version installed on our server is  v2.1.9-stable. 
To solve the problem, we have to extract one block at a time. That's inefficient
