### ISSUE TITLE
Error in exporting token

### ISSUE THREAD

**Issue by cxd1995** [blockchain-etl/ethereum-etl#159]
We are exporting Ethereum data using GETH.  When exporting the table Tokens, some error happened. The error is:  
**eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes**
Surprisingly the error only happened during specific blocks. It worked well for the first 200 thounsand blocks and happened after that
![image](https://user-images.githubusercontent.com/45622921/54280683-ff4a0300-45d2-11e9-927e-508c2d286ca6.png)

**Comment by medvedev1088** [comment]
Thanks for reporting it. Does the exporting continue after that exception or does the program crash? This exception is supposed to be ignored as stated in the message.

**Comment by cxd1995** [comment]
The exporting continued. And the token table exported is null.

**Comment by medvedev1088** [comment]
You can check if the token contract conforms to the standard https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md. If it does and the values returned by symbol, decimals, name functions are not null then it's probably a bug.

**Comment by cxd1995** [comment]
This is the exported token table from block 400,000 to block 600,000. 
Only 19 rows and address column were exported.

![image](https://user-images.githubusercontent.com/45622921/54284756-7d120c80-45db-11e9-85d3-e09af47ca9a7.png)

**Comment by fdecollibus** [comment]
@medvedev1088 does it work as well with geth 1.9.2-stable-e76047e9 ? I am getting thousands of these eth_abi.exceptions.InsufficientDataBytes: but there is no contract address, so I can't verify if it's normal behaviour or I am missing some data.

**Comment by medvedev1088** [comment]
@fdecollibus I added function name and contract address in the log message https://github.com/blockchain-etl/ethereum-etl/pull/189. An example log message is:

`An exception occurred in function totalSupply of contract 0xf4eCEd2f682CE333f96f2D8966C613DeD8fC95DD. This exception can be safely ignored.`

You would need to check out that branch to try it out.
