### ISSUE TITLE
Stopped Parity when exporting trace

### ISSUE THREAD

**Issue by cxd1995** [blockchain-etl/ethereum-etl#162]
We are using Parity to export the trace table. It worked well previously. But some error occurred recent days.
![image](https://user-images.githubusercontent.com/45622921/55447455-6b2df300-55f6-11e9-98d5-8ae271997a35.png)
![image](https://user-images.githubusercontent.com/45622921/55447508-8f89cf80-55f6-11e9-9156-2f92379684b6.png)
It seems that the synchronization has failed since the block number 7280086. Guess it may be caused the update of Ethereum client. And we empty the data and synchronize from the start. BUT the error is not solved.

**Comment by tokusyu** [comment]
Hi.
Which version of Parity are you using?
I have experienced similar problem recently, and restarting parity solved it.

I am using parity/parity:v2.3.2 from Official Docker Image.

**Comment by cxd1995** [comment]
Parity Ethereum version: 2.1.9-stable
Operating system: Linux
Installation: built from source
Fully synchronized: no
Network: ethereum
Restarted: yes

**Comment by tokusyu** [comment]
I'm not sure but how about upgrading to at least v2.2 series?

This release notes said v2.1 reached end of life.
https://github.com/paritytech/parity-ethereum/releases/tag/v2.2.7

It may relate to Constantinople postponement.

**Comment by cxd1995** [comment]
We will try. Will the synchronous block data be emptied after the update?
It is troublesome that we have to update the version of Parity frequently.
