### ISSUE TITLE
Error Exporting ERC20 and ERC721 transfers

### ISSUE THREAD

**Issue by lanhray** [blockchain-etl/ethereum-etl#171]
![Screen Shot 2019-05-06 at 1 48 09 PM](https://user-images.githubusercontent.com/38264137/57244152-cee87900-7005-11e9-8ec7-a9d2c4ebec63.png)

**Comment by medvedev1088** [comment]
Thanks for reporting this. The messages about missing modules are expected and are warnings. The actual error message is missing on the screenshot, it should be at the very bottom of the output.
