### ISSUE TITLE
how to find succussful transaction without receipts?

### ISSUE THREAD

**Issue by cxd1995** [blockchain-etl/ethereum-etl#174]
Since the table receipt only offers the status value after block 4370000, how could we judge whether a transaction succeeds before the block 4370000? Maybe the trace table. But we notice that a transaction may have many records in the trace table. And a single error among the traces does not lead to failure and could also get successful transactions.

**Comment by medvedev1088** [comment]
You have to look at the `traces.status` column where `trace_address` is empty. Every transaction must have a single trace with empty `trace_address`. Its status should correspond to the transaction status.
