### ISSUE TITLE
bigquery-public-data.crypto_ethereum.token_transfers.values rounding and loss of precision

### ISSUE THREAD

**Issue by kushal256** [blockchain-etl/ethereum-etl#182]
Ethereum table `bigquery-public-data.crypto_ethereum.token_transfers`, column 'values' changed today - that field is being rounded prematurely and loosing data.  For example:
```
#standardSQL
SELECT * FROM `bigquery-public-data.crypto_ethereum.token_transfers` WHERE
block_timestamp >= "2019-07-17 00:00:00" AND block_timestamp < "2019-07-18 00:00:00" 
and transaction_hash='0xabf8d73447c8b8805196039702010c06201d65fe12e08bea2be2fd8cbf6d0ecc'
```
shows a value of `9.6301936323e+20` but it's really much longer see https://etherscan.io/tx/0xabf8d73447c8b8805196039702010c06201d65fe12e08bea2be2fd8cbf6d0ecc the value is `963.019363229999955968` - it's missing alot of digits.

if I search for previous day's blocks don't see the same issue, it's exact:
```
#standardSQL
SELECT * FROM `bigquery-public-data.crypto_ethereum.token_transfers` WHERE
block_timestamp >= "2019-07-16 00:00:00" AND block_timestamp < "2019-07-17 00:00:00" 
and transaction_hash='0xeb21e8068daa1f52560c954fcff80c164bfdefd10d629ceb284cd78070a14ca7'
LIMIT 1000
```
shows several values, none rounded: `1001999999999999999785`, `1002146638507112324228`, `4273822635772509999`
where these all match etherscan's precision

**Comment by medvedev1088** [comment]
Good catch! I'm working on it.

**Comment by kushal256** [comment]
Thanks!  Looks like the fix was applied 3 days ago, all looks good!

**Comment by medvedev1088** [comment]
Thanks for reporting this. Let me know if you find other issues.
