### ISSUE TITLE
How to find contract created in transactions?

### ISSUE THREAD

**Issue by cxd1995** [blockchain-etl/ethereum-etl#188]
I find an issue about contract creation in the transaction table. In the transaction when a contract is created, the user invoke contract creation and the to_address in the table is NULL. Then how could we figure out the address of the created contract?
@medvedev1088

**Comment by medvedev1088** [comment]
I think receipt_contract_address field is what you need.

**Comment by cxd1995** [comment]
Thank you. As you mentioned, we could figure out the contract created by user in receipts table. And the contracts created by other contracts could be figured out from traces table. But after we union the two kinds of contracts. The result is different from the contract table we extract by ETL?
Is there something wrong with the contract table?

**Comment by medvedev1088** [comment]
The contracts table is created from the traces table. The Parity traces miss contract addresses from failed contract creations, while transaction receipts include those addresses. This case is described here https://github.com/blockchain-etl/ethereum-etl/issues/134#issuecomment-443510181.

**Comment by cxd1995** [comment]
The trace table is hard to understand. 
I have read the answers in #134. We could only query all contract addresses from the trace table.
BUT It is still hard to figure out when these contracts are created and who created these contracts.

**Comment by medvedev1088** [comment]
The `from_address` is usually the external address or contract that created a contract. The `block_number` and `block_timestamp` is when it was created. Do you mean it's hard to understand the trace hierarchy in case they are nested?
