### ISSUE TITLE
geth crashing often

### ISSUE THREAD

**Issue by lastmjs** [blockchain-etl/ethereum-etl#196]
Hey! Great tool. It seems I can't grab more than about 10,000 records at a time from geth before it freezes up after a while...to be clear, I'm not grabbing all blocks at once, I'm trying to piece it up in 10,000 block chunks. I would love to do more, like 50,000 or 100,000 or 1,000,000, but geth just can't seem to handle it. Any suggestions? Or is there any way ethereum-etl could handle this situation better?

**Comment by medvedev1088** [comment]
Could you include the commands that you use? This might happen if the --batch-size option is too big.

**Comment by lastmjs** [comment]
Ah, I'm doing this:

```bash
export_blocks_and_transactions --start-block ${lastBlockNumberInPostgres} --end-block ${lastBlockNumberInPostgres + numBlocksToImportFromGeth - 1} --provider-uri ${process.env.QUERY_ETHERUM_GETH_RPC_ORIGIN} --blocks-output output/blocks.csv
```

I am not specifying the batch size. What is the default batch size? Any suggestions on a good batch size?

**Comment by lastmjs** [comment]
So now I'm wondering if there are defaults for `--batch-size` and `--max-workers`. It would be nice if the documentation could explain this

**Comment by medvedev1088** [comment]
The default for --batch-size is 100, --max-workers is 5. I've just created this PR to display default values when using `--help` https://github.com/blockchain-etl/ethereum-etl/pull/197.
