### ISSUE TITLE
empty to_address and unknown transactions

### ISSUE THREAD

**Issue by campfireman** [blockchain-etl/ethereum-etl#211]
Hey guys,
your tool is a great! I have a question and I don't know if it's related to your tool or to ethereum in general. I downloaded all transactions from march (approx. 22 million) and roughly 57.000 of them have empty to_address columns, and the ones i checked to not appear in the specified block on etherscan.

Any help and hints would be greatly appreciated, I'm really interested to find the reason!

EDIT: Source of the data was the infura API

**Comment by medvedev1088** [comment]
Most likely it's a contract creation transaction. Do you have an example row for this?

**Comment by campfireman** [comment]
Yes, those are indeed contract creations. Could not find/reproduce which ones were not indexed on etherscan. Probably a mistake on my side. Sorry for bothering and thanks for the quick reply!
