### ISSUE TITLE
Ethereum Classic Node Update for June Hardfork

### ISSUE THREAD

**Issue by gitr0n1n** [blockchain-etl/ethereum-etl#213]
Ethereum Classic is scheduled for a hardfork upgrade in early June, 2020. Please update your clients to a Phoenix compatible version. You can find compatible version numbers and guides here:

https://ethereumclassic.org/development/clients

Can you confirm your intent to upgrade for Google BigQuery Public Datasets? Thank you much.

Please note: OpenEthereum (ParityEthereum) has not made an official release since Parity handed control over to Gnosis. If you use that client, the guide provides instructions for updating the client without an official release.

**Comment by YazzyYaz** [comment]
Google BigQuery has already been confirmed as ready for Phoenix so this ticket isn't needed.
