### ISSUE TITLE
Excpetions raised when exporting blockchain data

### ISSUE THREAD

**Issue by SirFrankieCrisp** [blockchain-etl/ethereum-etl#227]
I have a geth node running on my Linux machine and am trying to export the data. I have installed ethereum-etl thorugh pypi and am trying to run follwing command:

` ethereumetl export_blocks_and_transactions --start-block 0 --end-block 500000 --provider-uri file://~/Documents/.ethereum/geth.ipc --blocks-output blocks.csv --transactions-output transactions.csv `

After running the command, I get a gazillion error messaged, the first one being
> Symbolic Execution not available: No module named 'mythril.ether'      

and then a lot of errors stemming from File "/home/frankie/.local/lib/python3.8/site-packages/ethereumetl/providers/ipc.py".

I have intalled mythril using pypi and also installed solidity.

**Comment by allenzhao** [comment]
Did you manage to solve this? I encountered a similar error when streaming the file and an installation of the package from the source solve the issue for me.

**Comment by medvedev1088** [comment]
@SirFrankieCrisp the `Symbolic Execution not available` errors are warning and can be ignored. They are produced by one of dependencies

**Comment by SirFrankieCrisp** [comment]
@medvedev1088 Okey, then I'll disregard that error. I also found out the other errors. It was totally my fault. The path to my geth.ipc was wrong... 🤦 Thanks!

**Comment by SirFrankieCrisp** [comment]
@allenzhao Do you mean buidling the mythril.ether package from source or ethereum-etl itself?
