### ISSUE TITLE
Symbolic Execution not available: No module named 'mythril.ether'

### ISSUE THREAD

**Issue by HaveYouTall** [blockchain-etl/ethereum-etl#234]
When I tried to execute this ethereumetl extract_csv_column --input transactions.csv --column hash --output transaction_hashes.txt, I got the wrong message bellow
```
Symbolic Execution not available: No module named 'mythril.ether'
```
And the transaction_hashes.txt file is empty! (It may cause by the empty transactions.csv) Can anyone help me with this? Thanks!

And by the way, I got the `transactions.csv` from this
```
$ ethereumetl export_blocks_and_transactions --start-block 0 --end-block 5000 \

> --provider-uri file:///toshiba/*******/ethereum/eth-mainnet-dataset/fast-dataset/geth.ipc \

> --blocks-output blocks.csv --transactions-output transactions.csv
```
And it also shows the same No module message. I'm not sure if this command is already got something wrong which leads to an empty `transactions.csv`. But the `blocks.csv` file does have something that seems well.
> where `/toshiba/*******/ethereum/eth-mainnet-dataset/fast-dataset/geth.ipc` is my geth.ipc path (******* means I just don't show all filenames here)

**Comment by medvedev1088** [comment]
The reason the files are empty is there are no transactions in the early Ethereum blocks.

You can ignore the warning, it's from a dependency library.

**Comment by HaveYouTall** [comment]
> The reason the files are empty is there are no transactions in the early Ethereum blocks.
> 
> You can ignore the warning, it's from a dependency library.

Thanks, I will try more blocks and see if it is going well.
