### ISSUE TITLE
Ethereum data export error

### ISSUE THREAD

**Issue by sznariOsmosis** [blockchain-etl/ethereum-etl#262]
When i use “ethereumetl export_all -s 0 -e 5999999 -b 100000 -p file://$HOME/Library/Ethereum/geth.ipc -o output”，The following error occurred：“ValueError: Unknown uri scheme /datalake/blockdata/geth.ipc”，Ask what is the reason

**Comment by medvedev1088** [comment]
Do you call it with `-p file://$HOME/Library/Ethereum/geth.ipc -o output` or with `-p /datalake/blockdata/geth.ipc -o output`?

**Comment by sznariOsmosis** [comment]
> 你叫它 with`-p file://$HOME/Library/Ethereum/geth.ipc -o output`还是 with `-p /datalake/blockdata/geth.ipc -o output`？
/datalake/blockdata/geth.ipc

**Comment by sznariOsmosis** [comment]
/datalake/blockdata/geth.ipc

**Comment by medvedev1088** [comment]
Try `-p file:///datalake/blockdata/geth.ipc -o output`

`file://` is the uri scheme

**Comment by sznariOsmosis** [comment]
> Try `-p file:///datalake/blockdata/geth.ipc -o output`
> 
> `file://` is the uri scheme

Thank you, and the export was successful, but there is a question, why my block.csv has data, but my transactions.csv data is empty.

**Comment by medvedev1088** [comment]
Likely because you're exporting some early blocks in which there were no transactions

**Comment by sznariOsmosis** [comment]
> Likely because you're exporting some early blocks in which there were no transactions

I understand ，why the end block I exported reported (ethereumetl export_all -s 0 -e 6830510 -b 100000 -p file:///datalake/blockdata/geth.ipc -o output): "Please confirm whether the ETH node Already synchronized", I am sure that these blocks are currently synchronized

**Comment by sznariOsmosis** [comment]
> Likely because you're exporting some early blocks in which there were no transactions

error：ethereumetl.misc.retriable_value_error.RetriableValueError: result is None in response {'jsonrpc': '2.0', 'id': 0,esult': None}. Make sure Ethereum node is synced.
process:> eth.syncing
{
  currentBlock: 7020052,
  highestBlock: 12925923,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 0
}

**Comment by medvedev1088** [comment]
Resolved here https://github.com/blockchain-etl/ethereum-etl/issues/265

**Comment by limingyang2020** [comment]
> 



> > Likely because you're exporting some early blocks in which there were no transactions
> 
> error：ethereumetl.misc.retriable_value_error.RetriableValueError: result is None in response {'jsonrpc': '2.0', 'id': 0,esult': None}. Make sure Ethereum node is synced. process:> eth.syncing { currentBlock: 7020052, highestBlock: 12925923, knownStates: 0, pulledStates: 0, startingBlock: 0 }

the same problem ,  what should i do 
ethereumetl.misc.retriable_value_error.RetriableValueError: result is None in response {'jsonrpc': '2.0', 'id': 0, 'result': None}. Make sure Ethereum node is synced.
An error occurred. Quitting.
