### ISSUE TITLE
Exporting ERC20 transfers : TypeError: __init__() got an unexpected keyword argument 'converters'

### ISSUE THREAD

**Issue by Noorah11** [blockchain-etl/ethereum-etl#272]
I am using the following command to export ethereum  data and using etl 1.7.3
ethereumetl export_all -c ethereum -p **** -s 12965000 -e 12965423 -b 100 -w 1 -o ./temp 
.The blocks and transactions are exported correctly, however, I get the following error while Exporting ERC20 transfers f
  File "/home/ubuntu/capp2/src/noorah/test/lib/python3.6/site-packages/ethereumetl/jobs/exporters/token_transfers_item_exporter.py", line 45, in token_transfers_item_exporter
    converters=converters
TypeError: __init__() got an unexpected keyword argument 'converters'

**Comment by medvedev1088** [comment]
Do you also have bitcoin-etl installed in the same Python setup? There is a package there `blockchainetl` that clashes with the same package here and could cause this error.

**Comment by Noorah11** [comment]
Yes. I do have the bitcoin-etl v1.4.0 installed. Any workarounds you suggest?

**Comment by medvedev1088** [comment]
> Yes. I do have the bitcoin-etl v1.4.0 installed. Any workarounds you suggest?

Try upgrading to bitcoin-etl v1.5.1 and see if it helps

**Comment by Noorah11** [comment]
Thank you. It worked for me
