### ISSUE TITLE
Addresses with a balance greater than 0

### ISSUE THREAD

**Issue by ghost** [blockchain-etl/ethereum-etl#280]
Hello. Help me make a query to export all addresses with a balance greater than 0.

**Comment by BirdyUK** [comment]
@Napulsnik The most basic query would be the following:

```
SELECT * 
FROM `bigquery-public-data.crypto_ethereum.balances` 
WHERE eth_balance > 0 
LIMIT 1000
```

Remember the Balance is stored in WEI and not Eth, if you want all balances is Ether you would need to run something like the following:

```
SELECT address, SUM(CAST(eth_balance AS FLOAT64) / POWER(10,18)) AS balance
FROM `bigquery-public-data.crypto_ethereum.balances` 
group by address
order by balance desc
LIMIT 1000
```


PS:  Im still learning myself so this might not be the best way to achieve the result you are asking for!

Thanks!

**Comment by ghost** [comment]
> @Napulsnik The most basic query would be the following:
> 
> ```
> SELECT * 
> FROM `bigquery-public-data.crypto_ethereum.balances` 
> WHERE eth_balance > 0 
> LIMIT 1000
> ```
> 
> Remember the Balance is stored in WEI and not Eth, if you want all balances is Ether you would need to run something like the following:
> 
> ```
> SELECT address, SUM(CAST(eth_balance AS FLOAT64) / POWER(10,18)) AS balance
> FROM `bigquery-public-data.crypto_ethereum.balances` 
> group by address
> order by balance desc
> LIMIT 1000
> ```
> 
> PS: Im still learning myself so this might not be the best way to achieve the result you are asking for!
> 
> Thanks!

Thank you.

**Comment by agoora** [comment]
Hello,

I want to know if someone can help me with the bigquery command, to extract all addresses with a balance  > 5 ethers,  from "bigquery-public-data.crypto_ethereum"

* Date : from 01/01/2017 until 01/2018
* Format : address, nonce, balance, date

Thanks.
