### ISSUE TITLE
documentation on schema fields

### ISSUE THREAD

**Issue by alexandersimoes** [blockchain-etl/ethereum-etl#286]
Hi, is there documentation on the specifics of each of the fields in the output CSVs? For example what exactly does the `transaction_type` refer to in the exported transactions.csv file created? I see in the schema the type of value it is (BIGINT) but I don't know an explanation of what the field means. Maybe there is documentation somewhere I'm missing? Thanks!

**Comment by medvedev1088** [comment]
Hello, there are field descriptions in BigQuery schema file https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/raw/schemas/transactions.json

**Comment by alexandersimoes** [comment]
Awesome thanks for sharing this! But I noticed for the `transaction_type` field that the description just says "Transaction Type" which isn't very useful. Looking deeper into general ethereum documentation I see the following:
>TYPES OF TRANSACTIONS
>On Ethereum there are a few different types of transactions:
>
> - Regular transactions: a transaction from one wallet to another.
> - Contract deployment transactions: a transaction without a 'to' address, where the data field is used for the contract code.

Which value in the output CSVs maps to which of these? I see `2` and `0` values (at least in the blocks I've exported).

**Comment by medvedev1088** [comment]
It's one of 0 (Legacy), 1 (Legacy), 2 (EIP-1559)

**Comment by alexandersimoes** [comment]
Thanks, closing now.
