### ISSUE TITLE
How are balances hydrated in BigQuery?

### ISSUE THREAD

**Issue by NickKelly1** [blockchain-etl/ethereum-etl#288]
Hello :wave:!

Love the project. Fantastic work.

I'm wondering how it hydrates and deduplicates balances in BigQuery? I haven't found a mention of balances within the code. A class or filename to look in would be sufficient!

**Comment by BirdyUK** [comment]
@NickKelly1 to be honest i have also been researching and looking into ETL a lot over the last few days and i think the balances in bigquery are computed from the following package: [ethereum-etl-airflow](https://github.com/blockchain-etl/ethereum-etl-airflow)

I could be wrong, i am by no means a pro and merely trying to learn / understand how ETL is used to form the end results in bigquery.

With that said all contributors appear to have done an amazing job, with @medvedev1088 writing some very detailed medium posts here:  [medium.com](https://evgemedvedev.medium.com/) also the following might be of interest: [how-to-query-balances-for-all-ethereum-addresses-in-bigquery](https://medium.com/google-cloud/how-to-query-balances-for-all-ethereum-addresses-in-bigquery-fb594e4034a7)

If you end up confirming this is the case and that balances are handled using the above airflow package that would be great, like i say im just a n00b round here trying to put the effort into learning :-)

**Comment by NickKelly1** [comment]
@BirdyUK you're right, balances are extracted in ethereum-etl-airflow.

I asked the same question in Nansen's Discord and Evgeny pointed me to [this file in ethereum-etl-airflow](https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/enrich/sqls/balances.sql). Very helpful!

This issue can be closed now 😊
