### ISSUE TITLE
eth-abi==1.3.0 and web3.py update and dependency issue

### ISSUE THREAD

**Issue by etc-chmod** [blockchain-etl/ethereum-etl#308]
Hello,

I greatly appreciate your projects and the code you provide. Experimenting with it I came to the point where it seems that your library requires eth-abi==1.3.0 (newest: 3.0.0) which in turn leads to web3.py version to be maxed out at 4.7.2 (newest: 5.27.0).

Probably this is only the tip of the iceberg, but since I got a security warning for websockets==6.0.0 as part of web3.py==4.7.2 I wanted to address this.

I could not find this topic within any issue or pull request and wanted to briefly now, whether I overlooked sth., whether you are planning to update this, or whether this update is not about to be addressed, just to plan ahead.

Any - even brief - answer would be greatly appreciated.

Kind regards
etc

**Comment by ninaleechie** [comment]
I have a similar dependency issue.  Python3.8 on Ubuntu 20.04.
after running the pip3 install -e . on a fresh clone of the repository, I see:
ERROR: rlp 3.0.0 has requirement eth-utils<3,>=2.0.0, but you'll have eth-utils 1.10.0 which is incompatible.
ERROR: eth-rlp 0.3.0 has requirement eth-utils<3,>=2.0.0, but you'll have eth-utils 1.10.0 which is incompatible.
Then if I update eth-utils to 2.0.0, I get this:
ERROR: web3 4.7.2 has requirement eth-utils<2.0.0,>=1.0.1, but you'll have eth-utils 2.0.0 which is incompatible.
ERROR: eth-keys 0.2.4 has requirement eth-utils<2.0.0,>=1.3.0, but you'll have eth-utils 2.0.0 which is incompatible.
ERROR: eth-keyfile 0.5.1 has requirement eth-utils<2.0.0,>=1.0.0-beta.1, but you'll have eth-utils 2.0.0 which is incompatible.
ERROR: eth-account 0.3.0 has requirement eth-utils<2,>=1.0.2, but you'll have eth-utils 2.0.0 which is incompatible.
ERROR: eth-abi 1.3.0 has requirement eth-typing<3.0.0,>=2.0.0, but you'll have eth-typing 3.0.0 which is incompatible.
ERROR: eth-abi 1.3.0 has requirement eth-utils<2.0.0,>=1.2.0, but you'll have eth-utils 2.0.0 which is incompatible.
ERROR: ethereum-etl 1.10.0 has requirement eth-utils==1.10.0, but you'll have eth-utils 2.0.0 which is incompatible.

**Comment by medvedev1088** [comment]
Thanks for reporting it. We definitely need to upgrade the dependencies and make the changes accordingly where api compatibility is broken.

**Comment by magnitis** [comment]
>ERROR: eth-rlp 0.3.0 has requirement eth-utils<3,>=2.0.0, but you'll have eth-utils 1.10.0 which is incompatible.

@ninaleechie I faced a similar issue with the `eth-rlp` library while setting up under the same environment (Python3.8 on Ubuntu 20.04).
As a temporary fix, I downgraded to `eth-rlp==0.2.1`.

**Comment by alexleventer** [comment]
@medvedev1088 - I can take this issue?

**Comment by medvedev1088** [comment]
@alexleventer that would be great, thanks!

**Comment by dbfreem** [comment]
following. I have worked on web3.py some and would be interested if there are breaking changes that cause you problems with that big of a version move. web3.py 4.7.2 was released September 25, 2018 so I suspect this will have bigger impacts than just upgrading the dependencies. I am happy to help if I can.

**Comment by dbfreem** [comment]
Also, one thing to keep in mind is that web3.py dropped python 3.6 support in this [commit](https://github.com/ethereum/web3.py/commit/1284329406d8ae34766de65561229598129a1d19). So this upgrade would require ethereum etl to drop 3.6 support as well.

**Comment by jerrinot** [comment]
Hello, I understood blockchain-etl does not work on Python 3.10 and this PR could make it compatible again. 

It's because the old web3 transitively depends on an ancient version of eth-account, which does not have this [tiny 4 letters fix](https://github.com/ethereum/eth-account/commit/ccff52439b6bb0101b6f3f7c212e40f4cd8f1d92) merged and apparently Python 3.10 drop support for the old & deprecated collection API.

**Comment by dbfreem** [comment]
Hey @medvedev1088  this issue can probably be closed.

**Comment by etc-chmod** [comment]
Just saw what you did. Will upgrade in the next weeks. 
Thank you so much for your work!
