### ISSUE TITLE
Verifying list of holders

### ISSUE THREAD

**Issue by yaseenkhanmohmand** [blockchain-etl/ethereum-etl#329]
For each collection can we please make sure that we have the correct list of holders. We can do this by comparing the list of holders with information from etherscan.

![image](https://user-images.githubusercontent.com/34256008/163114403-39e5e50e-b818-4fa3-b555-ce400ec43b2f.png)

|https://etherscan.io/token/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#balances

This is an important check because if we are getting our information from moralis api, one of it's API's does not give information on mints.

**Comment by medvedev1088** [comment]
Not related to this repository
