### ISSUE TITLE
Getting streaming data of NFT events on Eth blockchain

### ISSUE THREAD

**Issue by yaseenkhanmohmand** [blockchain-etl/ethereum-etl#330]
It seems we currently have a static list of projects on nft-hunter, can we make it so that we can get all Eth NFTs on the website. This will mean that viewers will have the ability to detect activity on new project as soon as new projects hit the market. 

This will require using the nft/transfers api from moralis, which does not need an NFT contract address to provide transfers information. It instead only needs the block number and then provides live data based on what is happening on the block.

**Comment by medvedev1088** [comment]
Not related to this repository
