### ISSUE TITLE
BCHP metric bug

### ISSUE THREAD

**Issue by yaseenkhanmohmand** [blockchain-etl/ethereum-etl#331]
When calculating the BCHP metric the formula is:

Number of holders that hold atleast one Blue chip project (excluding the bluechip project in questions*)/
total number of holders.

attaching image of the error: 
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/34256008/163115146-77604623-6e88-4c36-a0da-3448d22035c7.png">

The percentage on Azuki should not be 100%, we should not be counting the number of holders that hold azuki when calculating this percentage for azuki.

**Comment by medvedev1088** [comment]
Not related to this repository
