### ISSUE TITLE
Holding chart improvements

### ISSUE THREAD

**Issue by yaseenkhanmohmand** [blockchain-etl/ethereum-etl#332]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/34256008/163115339-b6dd0a57-a367-478c-b189-ea27033f16e7.png">

Can we show more historic data on this chart? This is currently only showing data 2022-04-06 onwards, can we show all historic data for any project.

This chart should have two lines:
1 line that shows historic floor price.

1 line that shows the historic Blue Chip Holders percentage.

**Comment by medvedev1088** [comment]
Not related to this repository
