### ISSUE TITLE
Holding Median Bug

### ISSUE THREAD

**Issue by yaseenkhanmohmand** [blockchain-etl/ethereum-etl#336]
how is this metric being calculated?

Ideally we want to calculate:

For any project, what is the median amount of time it's holders has held a project in the past.

for example if a project has 5 holders:

holder 1: has held all it's nfts for a median of 5 days before selling.
holder 2: has held all it's nfts for a median of 10 days before selling.
holder 3: has held all it's nfts for a median of 15 days before selling.
holder 4: has held all it's nfts for a median of 7 days before selling.
holder 5: has held all it's nfts for a median of 1 days before selling.

Median time for holders for the project will be:
Median of 5,10,15,7,1

**Comment by medvedev1088** [comment]
Not related to this repository
