### ISSUE TITLE
Enable scrolling on the front end.

### ISSUE THREAD

**Issue by yaseenkhanmohmand** [blockchain-etl/ethereum-etl#337]
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/34256008/163118471-a1c09640-b9a6-44f6-aad2-e3aea5df0e24.png">

All column names should be clickable on the front end. Clicking them should sort the column quickly in Ascending or descending order.

Currently it takes very long to sort these projects.

**Comment by medvedev1088** [comment]
Hi, is it in relation to this website https://www.nfthunter.app/ ?

**Comment by yaseenkhanmohmand** [comment]
This is for nft-hunter.xyz

**Comment by medvedev1088** [comment]
This repository is not related to nft-hunter.xyz I believe

**Comment by yaseenkhanmohmand** [comment]
Can you add me to the https://nft-hunter.xyz/ rep?

Also is it possible to all these tickets to that rep?

**Comment by medvedev1088** [comment]
Please contact people at https://nft-hunter.xyz/. I unfortunately don't know their repository
