### ISSUE TITLE
Filters on the front end UI

### ISSUE THREAD

**Issue by yaseenkhanmohmand** [blockchain-etl/ethereum-etl#338]
Lets have some basic filters on the front end.

E.g:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/34256008/163118683-4c31af2c-91a4-4fbd-902a-92bf47b5afb2.png">

And the ability to filter by median days held.

and BCHP

**Comment by medvedev1088** [comment]
Not related to this repository
