### ISSUE TITLE
Address not found

### ISSUE THREAD

**Issue by fulldecent** [blockchain-etl/ethereum-etl#355]
I put in the address for the first ERC-721 contract and did not see any results.

Is this ETL still active?

<img width="1509" alt="Screen Shot 2022-06-07 at 22 51 31" src="https://user-images.githubusercontent.com/382183/172521319-a1e09c88-7701-4cb5-b453-815f81133728.png">

**Comment by GauthamramRavichandran** [comment]
All the fields are in normalised form. So addresses would be in lowercases. Convert it into lowercase characters before querying.

**Comment by fulldecent** [comment]
Thank you. I fixed it with:

```sql
SELECT *
  FROM `bigquery-public-data.crypto_ethereum.contracts`
 WHERE address LIKE "0xe9e3f9cfc1a64dfca53614a0182cfad56c10624f"
```

---

In MySQL, rows can be specified with a case insensitive collation. Whoever owns this data model might consider something like that.

Also especially because in Ethereum communities, the "normalized form" is sometimes considered as the EIP-55 rather than the lowercase version.
