### ISSUE TITLE
Ability to export or query all ever used addresses

### ISSUE THREAD

**Issue by Hanoosh** [blockchain-etl/ethereum-etl#37]
can it be used to dump all ever used addresses ?

i know i can do that using "--transactions-output transactions.csv" and then extract tx_from and tx_to then sort and remove duplicates 

but how to get the addresses from tx_input that are used in contracts ?
**EDIT:** now i saw that i can use erc20_transfers.csv erc20_from,erc20_to 
and how about the miners ?
**EDIT:** i can use blocks.csv block_miner 

any more addresses hidden in the blockchain ?

**Comment by medvedev1088** [comment]
1. When I add internal transactions you will be able to query all addresses that have ever had non-zero Ether balance and all contracts.
2. If you add erc20_transfers to_address/from_address you will get all addresses that have ever had non-zero Ether/token balance and all contracts.
3. If you use 4byte.directory data and parse transaction inputs you can also add addresses not included in (1) and (2) but have been used in transactions for some purposes.

**Comment by medvedev1088** [comment]
Done https://medium.com/google-cloud/how-to-query-balances-for-all-ethereum-addresses-in-bigquery-fb594e4034a7
