### ISSUE TITLE
can't support proxy contract erc20

### ISSUE THREAD

**Issue by SuperEdison** [blockchain-etl/ethereum-etl#414]
I looked at the source code and found that bytecode is used to judge whether it is erc20, but many contracts currently use the proxy contract upgrade solution to deploy the contract, which makes it impossible to judge whether it is erc20

**Comment by l-jhon** [comment]
I think you can consider the token_transfers as ecr20, right?

**Comment by SuperEdison** [comment]
yes

> I think you can consider the token_transfers as ecr20, right?
