### ISSUE TITLE
Add optional parameter "timezone" to get_block_range_for_date.py

### ISSUE THREAD

**Issue by tokusyu** [blockchain-etl/ethereum-etl#86]
It would be nice if we can pass timezone parameter to get_block_range_for_date.py as an option because I usually use JST(+9) in analyzing rather than UTC.

**Comment by medvedev1088** [comment]
Good idea.

**Comment by tokusyu** [comment]
I solved this problem using Apache Spark with additional tasks.
I changed my mind that this issue should be solved outside this software.
Thanks.
