### ISSUE TITLE
error in get blocks by date

### ISSUE THREAD

**Issue by domatka78** [blockchain-etl/ethereum-etl#90]
Hi, I get the following error, wonder if you can advise:
$ python get_block_range_for_date.py --provider-uri=https://mainnet.infura.io --date 2018-01-01
Traceback (most recent call last):
  File "get_block_range_for_date.py", line 50, in <module>
    start_block, end_block = eth_service.get_block_range_for_date(args.date)
  File "D:\git\ethereum-etl-master_230818\ethereumetl\service\eth_service.py", line 35, in get_block_range_for_date
    start_datetime = datetime.combine(date, datetime.min.time(), tzinfo=timezone.utc)
TypeError: combine() takes at most 2 arguments (3 given)

Thank you!

**Comment by medvedev1088** [comment]
Thanks for reporting this! I will try to fix it in 3.5.4

**Comment by medvedev1088** [comment]
Fixed.
