### ISSUE TITLE
Is it possible to export transactions by given address only (to or from)?

### ISSUE THREAD

**Issue by domatka78** [blockchain-etl/ethereum-etl#98]

**Comment by ArtemBernatskyy** [comment]
+1

**Comment by medvedev1088** [comment]
Unfortunately, the JSON RPC API doesn't provide this capability.

**Comment by ArtemBernatskyy** [comment]
It could be done via Ethereum in BigQuery.
https://cloud.google.com/blog/products/data-analytics/ethereum-bigquery-public-dataset-smart-contract-analytics

Note: you need to input eth addresses in lowercase )
